# Generated by Django 5.2.11 on 2026-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_salesperson_alter_lead_status_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
